spring:
  application:
    name: jnstore-sboot-orch

jwt:
  secret: "SecretoMuitoLongoParaSerSeguroNaoUseEmProducaoPorFavorAltereIsso"
  expiration: "86400000" # 24 horas

server:
  port: 8081

feign:
  client:
    produto:
      url: http://localhost:8082
    venda:
      url: http://localhost:8083
    auth:
      url: http://localhost:8084